### ISSUE TITLE
Asking about how to generate javadoc

### ISSUE THREAD

**Issue by ziyuanzhao2000** [Nekoyue/ForgeJavaDocs-NG#1]
Hi Neko, I was trying to generate the javadoc htmls for the latest version of forge. I got the jar file for the source, and then unzipped it and ran the javadoc from commandline, but it doesn't quite work. I was wondering how you got to generate these docs on your git. Thank you!

**Comment by Nekoyue** [comment]
Hi Ziyuan, thanks for opening this issue. I used IntelliJ IDEA's build-in javadoc generator with Forge's [source code](https://github.com/MinecraftForge/MinecraftForge) to generate HTML files. Detailed procedures are described below.

Clone the repo to your local machine. You may change the branch name to clone other versions.
`git clone --branch 1.16.x https://github.com/MinecraftForge/MinecraftForge.git`

Import Forge to IntelliJ IDEA. Simply drag & drop the Forge folder into IntelliJ IDEA's starting menu.

(Optional) Run `./gradlew setup` to set up the project. This will download Minecraft's source codes and mappings. Skip this step if you only need javadoc from package `net.minecraftforge.*` (i.e., you don't need javadoc from `com.mojang.*` or `net.minecraft.*`)

Delete `Forge/projects/clean` folder since it causes conflicts during javadoc generation.

Open IntelliJ IDEA, click `Menu Bar` - `Tools` - `Generate JavaDoc...` Click OK after setting all parameters. Wait, and all done.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/46295491/112622851-930f6480-8e66-11eb-910e-d7ce151642be.png">


I never tried to generate HTML with javadoc command in command line, but it should also work. I hope this may help you!

**Comment by ziyuanzhao2000** [comment]
Thank you so much for your quick response and detailed explanation. You are absolutely correct. I should have done the javadoc using gradle instead of at command line, where it's reporting missing some related packages outside of Forge. Anyway, I used IntelliJ and the above steps work nicely. And thanks for the tip to delete the /clean folder
